model_args:
  decoder_depth: 8
  decoder_embed_dim: 512
  decoder_num_heads: 16
  depth: 12
  embed_dim: 768
  img_size: 224
  in_chans: 6
  num_frames: 1
  num_heads: 12
  patch_size: 16
  tubelet_size: 1
